/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;

/**
 *
 * @author Tama
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btnglassfish = new javax.swing.JButton();
        btnjavaee = new javax.swing.JButton();
        btnpostgresql = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lblglassfish = new javax.swing.JLabel();
        lbljavaee = new javax.swing.JLabel();
        lblpostgresql = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnglassfish.setText("Glassfish");
        btnglassfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnglassfishActionPerformed(evt);
            }
        });
        buttonPanel.add(btnglassfish);

        btnjavaee.setText("JavaEE");
        btnjavaee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjavaeeActionPerformed(evt);
            }
        });
        buttonPanel.add(btnjavaee);

        btnpostgresql.setText("PostgreSQL");
        btnpostgresql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostgresqlActionPerformed(evt);
            }
        });
        buttonPanel.add(btnpostgresql);

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnexit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblglassfish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblglassfish.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tama\\Music\\glassfish.jpg")); // NOI18N
        lblglassfish.setMaximumSize(new java.awt.Dimension(300, 300));
        lblglassfish.setMinimumSize(new java.awt.Dimension(300, 300));
        imagePanel.add(lblglassfish, "0");

        lbljavaee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljavaee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tama\\Music\\javaee.jpg")); // NOI18N
        imagePanel.add(lbljavaee, "1");

        lblpostgresql.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpostgresql.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tama\\Music\\postgresql.jpg")); // NOI18N
        imagePanel.add(lblpostgresql, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnglassfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnglassfishActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_btnglassfishActionPerformed

    private void btnjavaeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjavaeeActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnjavaeeActionPerformed

    private void btnpostgresqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostgresqlActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_btnpostgresqlActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnglassfish;
    private javax.swing.JButton btnjavaee;
    private javax.swing.JButton btnpostgresql;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lblglassfish;
    private javax.swing.JLabel lbljavaee;
    private javax.swing.JLabel lblpostgresql;
    // End of variables declaration//GEN-END:variables
}
